### ISSUE TITLE
RunStatusTimestamps are wrong/out of date

### ISSUE THREAD

**Issue by trv-ddross** [hashicorp/go-tfe#226]
Hi, we are investigating using this API for a Terraform Enterprise installation and noticed some anomalies that we hope can be easily explained/solved.

The TFE API returns a status timestamp object as shown below, and the go-tfe API has different attributes, thus some are not populated (expected).
"status-timestamps": {
                "applied-at": "2021-05-27T17:51:56+00:00",
                "planned-at": "2021-05-27T17:45:06+00:00",
                "applying-at": "2021-05-27T17:50:54+00:00",
                "planning-at": "2021-05-27T17:44:18+00:00",
                "confirmed-at": "2021-05-27T17:50:50+00:00",
                "plan-queued-at": "2021-05-27T17:44:14+00:00",
                "apply-queued-at": "2021-05-27T17:50:51+00:00",
                "plan-queueable-at": "2021-05-27T17:44:12+00:00",
                "policy-checked-at": "2021-05-27T17:45:16+00:00"
            },

go-tfe returns timestamps such as QueuedAt, FinishedAt, ErroredAt. Our TFE version 202104-1 does not have these properties. Is this API coded against a specific version of Terraform Cloud?

Thanks

Don

**Comment by chrisarcand** [comment]
Hi!

Thanks for reporting this; the short answer is that these anomalies are bugs! The client here is always (hopefully!) intended to match Terraform Cloud and by extension the latest version of Terraform Enterprise. Your TFE version is very current and these timestamps should match [the existing documented run states.](https://www.terraform.io/docs/cloud/api/run.html#run-states)

It looks like these struct fields were erroneously added in the original iteration of this client years ago, and have managed to stick around and cause confusion. They're also quite out of date, as several timestamps with various run phases have been added to Terraform Cloud/Enterprise since this struct was added.

This struct can be updated and the (broken) fields can be removed.
