### ISSUE TITLE
[Question] Pointers vs Literals in certain Option initializations

### ISSUE THREAD

**Issue by straubt1** [hashicorp/go-tfe#506]
During a refactor of my code I found a few commands that still leverage pointers instead of literals in the creation of `AdminTerraformVersionCreateOptions` type options.

Is this intended to be this way, most other structs seem to not require the `tfe.String()` type initialization.

```
tfv, err := client.Admin.TerraformVersions.Create(ctx, tfe.AdminTerraformVersionCreateOptions{
Version:  tfe.String(version),
URL:      tfe.String(url),
Sha:      tfe.String(sha),
Official: tfe.Bool(isOfficial),
Enabled:  tfe.Bool(isEnabled),
Beta:     tfe.Bool(isBeta),
})
```

**Comment by brandonc** [comment]
Typically, we don't use pointers for required values (such as Version, URL, Sha in this particular example) It appears that these (and potentially others!) were not changed at the 1.0 release.

Unfortunately, if we wanted to fix the inconsistencies on the public interface, we'd need to rev the version to 2.0. We have to be careful when changing these universally, though, because we sometimes utilize pointers for optional (omitempty) string fields because occasionally an empty string should be differentiated on the API.

I will note this for a future breaking version release! Thanks, Tom
