### ISSUE TITLE
Filter active runs with status exclusion or list of inclusions

### ISSUE THREAD

**Issue by manjinder-mckc** [hashicorp/go-tfe#646]
Is it currently possible to filter all active runs from a workspace ? perhaps by providing a list of statuses, or the other way around, by providing exclusion statuses. For example, I need to fetch all runs that have any status other than "planned", "planned and finished" and "applied"

**Comment by nfagerlund** [comment]
Hello! Yes, this is totally possible: the string value for the Status field in `tfe.RunListOptions` can be a comma-separated list of statuses, which results in a list of runs that are in any of the requested statuses. 

(There's no way to do an exclusion list I'm afraid, so the exact task you're doing is a bit more awkward, but at least it's doable by looking at the list of status constants and compiling a list yourself.)

A working example:

```go
package main

import (
	"context"
	"fmt"

	// "os"
	"strings"

	tfe "github.com/hashicorp/go-tfe"
)

func main() {
	client, err := tfe.NewClient(nil) // use env vars
	if err != nil {
		panic(err)
	}

	ctx := context.Background()

	statuses := []string{
		string(tfe.RunCanceled),
		string(tfe.RunDiscarded),
	}
	runs, err := client.Runs.List(ctx, "WORKSPACE ID REDACTED", &tfe.RunListOptions{Status: strings.Join(statuses, ",")})
	if err != nil {
		panic(err)
	}
	// do something more interesting than print a slice of pointers, but you get the idea
	fmt.Printf("Here's runs: %#v", runs)
}
```

I ran this against a workspace with 12 discarded runs and 1 cancelled run, and sure enough, I got a list of 13 runs back. 

This "use comma list for an OR filter" behavior is definitely intentional and ought to be documented in both the raw TFC API docs and the go client docs, but it's not. I'll leave this issue open as a placeholder while I do some docs updates tomorrow.

**Comment by manjinder-mckc** [comment]
> Hello! Yes, this is totally possible: the string value for the Status field in `tfe.RunListOptions` can be a comma-separated list of statuses, which results in a list of runs that are in any of the requested statuses.
> 
> (There's no way to do an exclusion list I'm afraid, so the exact task you're doing is a bit more awkward, but at least it's doable by looking at the list of status constants and compiling a list yourself.)
> 
> A working example:
> 
> ```go
> package main
> 
> import (
> 	"context"
> 	"fmt"
> 	"strings"
> 
> 	tfe "github.com/hashicorp/go-tfe"
> )
> 
> func main() {
> 	client, err := tfe.NewClient(nil) // use env vars
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	ctx := context.Background()
> 
> 	statuses := []string{
> 		string(tfe.RunCanceled),
> 		string(tfe.RunDiscarded),
> 	}
> 	runs, err := client.Runs.List(ctx, "WORKSPACE ID REDACTED", &tfe.RunListOptions{Status: strings.Join(statuses, ",")})
> 	if err != nil {
> 		panic(err)
> 	}
> 	// do something more interesting than print a slice of pointers, but you get the idea
> 	fmt.Printf("Here's runs: %#v", runs)
> }
> ```
> 
> I ran this against a workspace with 12 discarded runs and 1 cancelled run, and sure enough, I got a list of 13 runs back.
> 
> This "use comma list for an OR filter" behavior is definitely intentional and ought to be documented in both the raw TFC API docs and the go client docs, but it's not. I'll leave this issue open as a placeholder while I do some docs updates tomorrow.

sounds good, thanks. 
Somewhere in the future, I think it would be a value add to offer exclusion option in List method as it'd apparently make logic in consumer functions a little neater. But not a blocker so not a pressing need.
